Repository Codeit-Part3-Taskify/Taskify, pull requests merged in 2024-03, with the labels that each got.

#6 Docs: eslint-plugin-prettier 설치
  package-lock.json
  package.json
Labels: 세팅

#8 Docs: tailwind 적용
  src/App.jsx
  src/index.jsx
  src/styles/global.css
  tailwind.config.js
Labels: 문서

#13 Feat: 모달 레이아웃 및 컬럼 생성 모달 구현
  .eslintrc.json
  src/App.jsx
  src/components/Layout/Modal.tsx
  src/components/Modal/CreateColumn.tsx
  src/styles/global.css
Labels: 기능구현

#16 Style: 대시보드 공통 사이드바 퍼블리싱
  .eslintrc.json
  .github/pull_request_template.md
  public/images/Taskify.svg
  public/images/add-box.svg
  public/images/crown.svg
  public/images/logo.svg
  public/index.html
  src/App.jsx
  src/components/Dashboard/DashboardList.tsx
  src/components/Layout/SideBar.tsx
  src/components/Sidebar/AddDashboardHeader.tsx
  src/components/Sidebar/LogoText.tsx
  src/styles/global.css
  tailwind.config.js
Labels: 기능구현

#19 Feat: 라우터 기능 추가
  src/App.jsx
  src/components/Layout/SideBar.tsx
  src/components/MyPage/MyPage.tsx
  src/components/MyPage/PasswordFormArea.tsx
  src/components/MyPage/PasswordInputBox.tsx
  src/components/MyPage/ProfileFormArea.tsx
  src/components/MyPage/ProfileInputBox.tsx
  src/router/router.jsx
Labels: 기능구현

#22 Design: 버튼,인풋 css추가
  src/components/Layout/SideBar.tsx
  src/components/MyPage/PasswordInputBox.tsx
  src/components/MyPage/ProfileInputBox.tsx
  src/index.jsx
  src/styles/global.css
Labels: 기능구현

#26 Style: 대시보드 수정 페이지 퍼블리싱, Button 컴포넌트 생성
  src/assets/images/add-box-white.svg
  src/assets/images/arrow-backward-black.svg
  src/assets/images/arrow-backward-white.svg
  src/assets/images/arrow-forward-white.svg
  src/components/Buttons/Button.tsx
  src/components/Buttons/ModalResetButton.tsx
  src/components/Buttons/ModalSubmitButton.tsx
  src/components/Buttons/PagenationButtons.tsx
  src/components/Buttons/ReturnButton.tsx
  src/components/Dashboard/AddCard.tsx
  src/components/Dashboard/AddColumn.tsx
  src/components/EditDashboard/EditDashboardMembers.tsx
  src/components/EditDashboard/EditDashboardTitle.tsx
  src/components/EditDashboard/InvitationSettings.tsx
  src/components/EditDashboard/Lists/DashboardMemberList.tsx
  src/components/EditDashboard/Lists/InviteList.tsx
  src/components/Modal/AlertDeleteCard.tsx
  src/components/Modal/AlertPassword.tsx
  src/components/Modal/CreateCard.tsx
  src/components/Modal/CreateColumn.tsx
  src/components/Modal/CreateDashboard.tsx
  src/components/Modal/InviteMember.tsx
  src/components/Modal/ManageColumn.tsx
  src/components/Modal/UpdateCard.tsx
  src/components/MyPage/PasswordInputBox.tsx
  src/components/MyPage/ProfileInputBox.tsx
  src/components/Profile/Profile.tsx
  src/pages/Dashboard/DashboardPage.tsx
  src/pages/EditDashboard/EditDashboardPage.tsx
  src/router/router.jsx
  src/styles/global.css
  src/types/buttonTypes.ts
Labels: 기능구현

#29 Feature/task 23
  .eslintrc.json
  package-lock.json
  package.json
  src/App.jsx
  src/apis/createCard.ts
  src/apis/getDashboards.ts
  src/apis/readCardList.ts
  src/apis/readColumnList.ts
  src/components/Buttons/ModalResetButton.tsx
  src/components/Dashboard/Card/AddCard.tsx
  src/components/Dashboard/Card/Card.tsx
  src/components/Dashboard/Card/Cards.tsx
  src/components/Dashboard/Cards.tsx
  src/components/Dashboard/Column.tsx
  src/components/Dashboard/Column/AddColumn.tsx
  src/components/Dashboard/Column/Column.tsx
  src/components/Dashboard/Column/ColumnInfo.tsx
  src/components/Dashboard/ColumnInfo.tsx
  src/components/Dashboard/DashboardList.tsx
  src/components/Layout/Modal.tsx
  src/components/Modal/Card/AlertDeleteCard.tsx
  src/components/Modal/Card/CardDetail.tsx
  src/components/Modal/Card/CreateCard.tsx
  src/components/Modal/Card/UpdateCard.tsx
  src/components/Modal/Column/CreateColumn.tsx
  src/components/Modal/Column/ManageColumn.tsx
  src/components/Modal/Container/ModalContainer.tsx
  src/components/Modal/CreateCard.tsx
  src/components/Modal/LabelAndInput/LabelAndInput.tsx
  src/hooks/useCardList.ts
  src/pages/Dashboard/DashboardPage.tsx
  src/pages/Dashboard/MyDashboardPage.tsx
  src/router/router.jsx
  src/store/store.ts
  src/types/cardTypes.ts
  src/types/columnTypes.ts
  src/types/modalTypes.ts
  src/utils/selectModal.tsx
  tailwind.config.js
Labels: 기능구현, Task

#31 Feat: 대시보드 제목/색상 수정 구현
  src/apis/getDashboardDetails.ts
  src/apis/putDashboardTitle.ts
  src/components/ColorSelector/ColorSelector.tsx
  src/components/Dashboard/DashboardItem.tsx
  src/components/EditDashboard/EditDashboardTitle.tsx
  src/components/Modal/CreateDashboard.tsx
  src/hooks/useEditDashboardTitle.ts
  src/router/router.jsx
  src/utils/useMutateDashboardTitle.ts
  tailwind.config.js
Labels: 기능구현, Task

#33 Feature/task 30
  src/apis/createColumn.ts
  src/apis/deleteColumn.ts
  src/apis/readCardList.ts
  src/apis/readColumnList.ts
  src/apis/updateColumn.ts
  src/components/Buttons/ModalSubmitButton.tsx
  src/components/Dashboard/Card/AddCard.tsx
  src/components/Dashboard/Card/Card.tsx
  src/components/Dashboard/Card/Cards.tsx
  src/components/Dashboard/Column/AddColumn.tsx
  src/components/Dashboard/Column/ColumnInfo.tsx
  src/components/Modal/Card/CreateCard.tsx
  src/components/Modal/Card/UpdateCard.tsx
  src/components/Modal/Column/AlertDeleteCard.tsx
  src/components/Modal/Column/CreateColumn.tsx
  src/components/Modal/Column/ManageColumn.tsx
  src/components/Modal/LabelAndInput/LabelAndInput.tsx
  src/hooks/useCreateColumn.ts
  src/hooks/useManageColumn.ts
  src/pages/Dashboard/DashboardPage.tsx
  src/store/store.ts
  src/types/cardTypes.ts
  src/types/columnTypes.ts
  src/utils/selectModal.tsx
Labels: 기능구현, Task

#35 [Design] mypage 디자인 마무리
  src/App.jsx
  src/apis/postPassword.tsx
  src/assets/images/cross-button.svg
  src/components/Buttons/Button.tsx
  src/components/MyPage/PasswordFormArea.tsx
  src/components/MyPage/PasswordInputBox.tsx
  src/components/MyPage/ProfileFormArea.tsx
  src/components/MyPage/ProfileInputBox.tsx
  src/global.css
  src/index.jsx
Labels: 기능구현, Task

#37 Feat: 대시보드 구성원/초대 기능 구현
  src/apis/axiosInstance.ts
  src/apis/createCard.ts
  src/apis/createColumn.ts
  src/apis/createDashboards.ts
  src/apis/deleteColumn.ts
  src/apis/deleteDashboard.ts
  src/apis/deleteDashboardInvitation.ts
  src/apis/deleteDashboardMember.ts
  src/apis/getDashboardDetails.ts
  src/apis/getDashboardInvitations.ts
  src/apis/getDashboardMembers.ts
  src/apis/getDashboards.ts
  src/apis/postDashboardInvitation.ts
  src/apis/putDashboardTitle.ts
  src/apis/readCardList.ts
  src/apis/readColumnList.ts
  src/apis/updateColumn.ts
  src/components/Buttons/PagenationButtons.tsx
  src/components/Buttons/ReturnButton.tsx
  src/components/ColorSelector/ColorSelector.tsx
  src/components/Dashboard/DashboardItem.tsx
  src/components/EditDashboard/EditDashboardMembers.tsx
  src/components/EditDashboard/EditDashboardTitle.tsx
  src/components/EditDashboard/InvitationSettings.tsx
  src/components/EditDashboard/Lists/DashboardMemberList.tsx
  src/components/EditDashboard/Lists/InviteList.tsx
  src/components/Modal/InviteMember.tsx
  src/components/Profile/Profile.tsx
  src/constants/colors.ts
  src/constants/common.ts
  src/constants/pagenation.ts
  src/hooks/useDeleteDashboard.ts
  src/hooks/useInviteMember.ts
  src/hooks/usePagenationDashboardInvitations.ts
  src/hooks/usePagenationDashboardMembers.ts
  src/hooks/useUpdateDashboardTitle.ts
  src/pages/EditDashboard/EditDashboardPage.tsx
  src/types/dashboardTypes.ts
  src/utils/handleError.ts
  src/utils/useMutateDashboardTitle.ts
Labels: 기능구현, Task

#38 Design: 로그인 페이지 디자인구현
  src/assets/images/eye.svg
  src/assets/images/none-eye.svg
  src/components/LogIn/LogInForm.tsx
  src/components/LogIn/SignUpForm.tsx
  src/components/LogIn/TaskifyLogo.tsx
  src/pages/LogIn/LogIn.tsx
  src/pages/SignUp/SignUp.tsx
  src/router/router.jsx
Labels: 기능구현

#42 Feature/task 34
  .eslintrc.json
  package-lock.json
  package.json
  src/apis/createCard.ts
  src/apis/createColumn.ts
  src/apis/deleteColumn.ts
  src/apis/deleteDashboard.ts
  src/apis/deleteDashboardInvitation.ts
  src/apis/deleteDashboardMember.ts
  src/apis/getDashboardDetails.ts
  src/apis/getDashboardInvitations.ts
  src/apis/getDashboardMembers.ts
  src/apis/getMemberList.ts
  src/apis/postDashboardInvitation.ts
  src/apis/putDashboardTitle.ts
  src/apis/readCardDetail.ts
  src/apis/readCardList.ts
  src/apis/updateCardData.ts
  src/apis/updateColumn.ts
  src/apis/uploadCardImage.ts
  src/assets/images/arrow-down-black.svg
  src/assets/images/stroke.svg
  src/components/Dashboard/Card/AddCard.tsx
  src/components/Dashboard/Card/Card.tsx
  src/components/Dashboard/Card/Cards.tsx
  src/components/Dashboard/Column/AddColumn.tsx
  src/components/Dashboard/Column/ColumnInfo.tsx
  src/components/Modal/Card/CardDetail.tsx
  src/components/Modal/Card/CreateCard.tsx
  src/components/Modal/Card/UpdateCard.tsx
  src/components/Modal/Column/CreateColumn.tsx
  src/components/Modal/Column/ManageColumn.tsx
  src/components/Modal/LabelAndInput/LabelAndInput.tsx
  src/components/Profile/Profile.tsx
  src/components/Sidebar/AddDashboardHeader.tsx
  src/global.css
  src/hooks/useCreateColumn.ts
  src/hooks/useManageColumn.ts
  src/pages/EditDashboard/EditDashboardPage.tsx
  src/store/store.ts
  src/types/cardTypes.ts
  src/types/columnTypes.ts
  src/types/memberTypes.ts
  src/utils/checkColumnName.ts
Labels: 기능구현, Task

#47 Feat: 공통 컴포넌트(모달, 사이드바) 레이아웃 파일로 이동
  src/components/Layout/Layout.tsx
  src/components/Layout/SideBarLayout.tsx
  src/components/Sidebar/AddDashboardHeader.tsx
  src/pages/Dashboard/DashboardPage.tsx
  src/router/router.jsx
  src/store/store.ts
Labels: 버그

#48 Style: 대시보드 수정 페이지 반응형
  src/components/Buttons/ModalResetButton.tsx
  src/components/Buttons/ModalSubmitButton.tsx
  src/components/Buttons/PagenationButtons.tsx
  src/components/Buttons/ReturnButton.tsx
  src/components/ColorSelector/ColorSelector.tsx
  src/components/ColorSelector/DropdownColorSelector.tsx
  src/components/Dashboard/DashboardList.tsx
  src/components/EditDashboard/EditDashboardMembers.tsx
  src/components/EditDashboard/EditDashboardTitle.tsx
  src/components/EditDashboard/InvitationSettings.tsx
  src/components/EditDashboard/Lists/DashboardMemberList.tsx
  src/components/EditDashboard/Lists/InviteList.tsx
  src/components/Modal/Container/ModalContainer.tsx
  src/components/Modal/CreateDashboard.tsx
  src/components/Modal/InviteMember.tsx
  src/components/Profile/Profile.tsx
  src/pages/EditDashboard/EditDashboardPage.tsx
Labels: 버그, Task

#50 Feature/task 43
  src/apis/deleteCard.ts
  src/apis/deleteComment.ts
  src/apis/postComment.ts
  src/apis/readCardDetail.ts
  src/apis/readCommentList.ts
  src/apis/updateComment.ts
  src/components/Modal/Card/CardDetail.tsx
  src/components/Modal/Card/CommentBox.tsx
  src/components/Modal/Card/CommentList.tsx
  src/components/Modal/Card/CreateCard.tsx
  src/components/Modal/Card/DropDown.tsx
  src/components/Modal/Card/UpdateCard.tsx
  src/components/Modal/Column/CreateColumn.tsx
  src/components/Modal/Column/ManageColumn.tsx
  src/constants/inputstyle.ts
  src/types/commentTypes.ts
Labels: 기능구현, Task

#51 Feat: 랜딩 페이지 구현(퍼블리싱 + 반응형 + 링크이동)
  src/assets/images/Taskify-white.svg
  src/assets/images/create-column.png
  src/assets/images/dashboard-page.png
  src/assets/images/edit-dashboard-title.png
  src/assets/images/edit-members.png
  src/assets/images/envelope.svg
  src/assets/images/facebook.svg
  src/assets/images/instagram.svg
  src/assets/images/invitation-settings.png
  src/assets/images/landing.png
  src/assets/images/logo-white.svg
  src/components/Landing/Footer.tsx
  src/components/Landing/HeroHeader.tsx
  src/components/Landing/MainArticle.tsx
  src/components/Landing/Navbar.tsx
  src/components/Landing/OtherSections.tsx
  src/pages/Landing/LandingPage.tsx
  src/router/router.jsx
Labels: Task

#52 Feat: Navbar 구현
  src/apis/getDashboardInvitations.ts
  src/apis/getDashboardMembers.ts
  src/apis/getMyInfo.tsx
  src/components/Buttons/PagenationButtons.tsx
  src/components/Dashboard/DashboardList.tsx
  src/components/EditDashboard/EditDashboardMembers.tsx
  src/components/EditDashboard/InvitationSettings.tsx
  src/components/EditDashboard/Lists/DashboardMemberList.tsx
  src/components/Landing/OtherSections.tsx
  src/components/Layout/Layout.tsx
  src/components/Layout/NavbarLayout.tsx
  src/components/Modal/Card/CardDetail.tsx
  src/components/Modal/Card/CommentList.tsx
  src/components/Modal/InviteMember.tsx
  src/components/Navbar/DashboardMembers.tsx
  src/components/Navbar/DashboardTitle.tsx
  src/components/Navbar/NavButtons.tsx
  src/components/Profile/Profile.tsx
  src/hooks/useCalcVisibleMembers.ts
  src/hooks/useInviteMember.ts
  src/hooks/usePagenationDashboardMembers.ts
  src/hooks/useUpdateDashboardTitle.ts
  src/types/memberTypes.ts
  src/utils/handleError.ts
  tailwind.config.js
Labels: 기능구현, Epic

#56 Feature/fix
  src/apis/updateCardData.ts
  src/components/Dashboard/Card/AddCard.tsx
  src/components/Dashboard/Card/Card.tsx
  src/components/Dashboard/Card/Cards.tsx
  src/components/Dashboard/Column/AddColumn.tsx
  src/components/Dashboard/Column/Column.tsx
  src/components/Dashboard/Column/ColumnInfo.tsx
  src/components/Layout/Modal.tsx
  src/components/Modal/Card/CardDetail.tsx
  src/components/Modal/Card/CommentBox.tsx
  src/components/Modal/Card/CreateCard.tsx
  src/components/Modal/Card/UpdateCard.tsx
  src/components/Modal/Container/ModalContainer.tsx
  src/hooks/useCardCommon.ts
  src/hooks/useCommentBox.ts
  src/hooks/useCreateCard.ts
  src/hooks/useUpdateCard.ts
  src/pages/Dashboard/DashboardPage.tsx
  src/types/cardTypes.ts
Labels: 기능구현, Task

#57 Feat: 나의 대시보드페이지
  src/apis/getDashboards.ts
  src/apis/getMyInvitations.ts
  src/apis/putInvitations.ts
  src/assets/images/arrow-forward-black.svg
  src/assets/images/search.svg
  src/assets/images/unsubscribe.svg
  src/components/Dashboard/DashboardItem.tsx
  src/components/Dashboard/DashboardList.tsx
  src/components/Dashboard/MyDashboard/AddDashboard.tsx
  src/components/Dashboard/MyDashboard/Invitations.tsx
  src/components/Dashboard/MyDashboard/InvitationsItem.tsx
  src/components/Modal/Card/CreateCard.tsx
  src/components/Modal/Card/UpdateCard.tsx
  src/constants/pagenation.ts
  src/hooks/useMyInvations.ts
  src/hooks/usePagenationDashboardList.ts
  src/hooks/usePutMyInvations.ts
  src/pages/Dashboard/MyDashboardPage.tsx
  src/types/invitationsTypes.ts
Labels: 기능구현

#59 Feat: 초대받은 대시보드 검색어 필터링
  src/apis/getMyInvitations.ts
  src/components/Dashboard/MyDashboard/Invitations.tsx
  src/components/Dashboard/MyDashboard/InvitationsItem.tsx
  src/components/Layout/SideBarLayout.tsx
  src/components/Sidebar/LogoText.tsx
  src/hooks/useMyInvations.ts
Labels: 기능구현

#67 Update: Api&반응형디자인 마무리
  public/favicon.svg
  public/index.html
  src/apis/postImage.ts
  src/apis/putUserInfo.ts
  src/components/Layout/Modal.tsx
  src/components/LogIn/LogInForm.tsx
  src/components/LogIn/SignUpForm.tsx
  src/components/LogIn/TaskifyLogo.tsx
  src/components/Modal/Alert/AlertEmail.tsx
  src/components/Modal/Alert/AlertPassword.tsx
  src/components/Modal/Alert/SignUpConfirm.tsx
  src/components/MyPage/PasswordFormArea.tsx
  src/components/MyPage/ProfileFormArea.tsx
  src/pages/MyPage/MyPage.tsx
  tailwind.config.js
Labels: 기능구현, Epic

#66 Feat: 에러처리, 모달 닫힘기능, 카드 상세 기본 이미지
  src/components/Buttons/ReturnButton.tsx
  src/components/Dashboard/Card/AddCard.tsx
  src/components/Dashboard/Column/Column.tsx
  src/components/Modal/Card/CardDetail.tsx
  src/components/Modal/Card/CommentBox.tsx
  src/components/Modal/Card/CommentList.tsx
  src/components/Modal/Card/CreateCard.tsx
  src/components/Modal/Card/UpdateCard.tsx
  src/components/Modal/Container/ModalContainer.tsx
  src/global.css
  src/hooks/useCommentBox.ts
  src/hooks/useCreateCard.ts
  src/hooks/useUpdateCard.ts
  tailwind.config.js
Labels: 기능구현, Epic

#68 Feat: 대시보드 페이지 무한 스크롤
  package-lock.json
  package.json
  src/apis/readCardList.ts
  src/components/Dashboard/Card/Card.tsx
  src/components/Dashboard/Card/Cards.tsx
  src/components/Dashboard/Column/Column.tsx
  src/components/Layout/Layout.tsx
  src/components/Layout/NavbarLayout.tsx
  src/components/Modal/Card/CommentBox.tsx
  src/constants/pagenation.ts
  src/hooks/useCommentBox.ts
  src/hooks/useCreateCard.ts
  src/hooks/useDeleteDashboard.ts
  src/hooks/useInfiniteScrollColumn.ts
  src/hooks/useUpdateCard.ts
  src/pages/EditDashboard/EditDashboardPage.tsx
  tailwind.config.js
Labels: 기능구현, Task

#71 Hotfix: 배포 에러 수정
  src/components/Layout/NavbarLayout.tsx
  src/components/Modal/Card/CommentBox.tsx
  src/hooks/useDeleteDashboard.ts
  src/pages/EditDashboard/EditDashboardPage.tsx
  src/utils/handleError.ts
Labels: 버그

#76 Fix:마이페이지 이미지인풋수정
  package-lock.json
  package.json
  src/assets/images/x-button.svg
  src/assets/images/x-button2.svg
  src/components/LogIn/LogInForm.tsx
  src/components/MyPage/ProfileFormArea.tsx
  src/index.jsx
  src/pages/Dashboard/DashboardPage.tsx
  src/pages/Dashboard/MyDashboardPage.tsx
  src/pages/EditDashboard/EditDashboardPage.tsx
  src/pages/Landing/LandingPage.tsx
  src/pages/LogIn/LogIn.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/SignUp/SignUp.tsx
Labels: 기능구현, Epic

#77 Refactor: swipe 기능추가, 페이지별 NavBar 적용, 페이지네이션 버튼 ui 개선
  package-lock.json
  package.json
  src/apis/getDashboardDetails.ts
  src/assets/images/left-arrow.png
  src/assets/images/right-arrow.png
  src/components/Buttons/PagenationButtons.tsx
  src/components/Dashboard/DashboardList.tsx
  src/components/EditDashboard/EditDashboardMembers.tsx
  src/components/EditDashboard/InvitationSettings.tsx
  src/components/Layout/Layout.tsx
  src/components/Layout/NavbarLayout.tsx
  src/components/Navbar/DashboardTitle.tsx
  src/hooks/useCalcVisibleMembers.ts
  src/hooks/usePagenationDashboardInvitations.ts
  src/hooks/usePagenationDashboardList.ts
  src/hooks/usePagenationDashboardMembers.ts
  src/hooks/useSwipe.ts
  src/hooks/useUpdateDashboardTitle.ts
  src/pages/Dashboard/DashboardPage.tsx
Labels: 리팩토링, 기능구현

#78 Refactor: 쿠키에 토큰 저장, Nav바에 내 대시보드 가는 버튼 추가
  package-lock.json
  package.json
  src/apis/axiosInstance.ts
  src/components/Layout/NavbarLayout.tsx
  src/components/LogIn/LogInForm.tsx
  src/components/Navbar/NavButtons.tsx
  src/components/Sidebar/LogoText.tsx
Labels: 리팩토링
